services:
  db:
    image: postgres:17.4-alpine
    container_name: academy-quest-boss-lepan-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - rails-data:/var/lib/postgresql/data

volumes:
  rails-data:
