default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://localhost/academy_quest_boss_lepan" } %>

development:
  <<: *default
  database: academy_quest_boss_lepan_development

test:
  <<: *default
  database: academy_quest_boss_lepan_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") { "postgres://localhost/academy_quest_boss_lepan" } %>
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production
  cable:
    <<: *primary_production
